version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/php:7.2
    steps:
      - checkout
      - run:
          name: Install PHPUnit
          command: |
            wget https://phar.phpunit.de/phpunit-8.5.33.phar
      - run:
          name: Make PHPUnit executable
          command: |
            chmod +x ./phpunit-8.5.33.phar
      - run:
          name: Run PHPUnit
          command: |
            INTERCOM_PLUGIN_TEST=1 php ./phpunit-8.5.33.phar

workflows:
  sample:
    jobs:
      - build-and-test
